// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
void fun2();
extern "C" SEXP _pkg2_fun2() {
  BEGIN_CPP11
    fun2();
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_pkg2_fun2", (DL_FUNC) &_pkg2_fun2, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pkg2(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
